spring:
  application:
    name: metro-back
  datasource:
    url: 'jdbc:postgresql://localhost:5432/metro_back'
    username: 'postgres'
    password: 'postgres'
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: '/swagger-ui/'
metro:
  security:
    key-secret: 'moscowmetroisthebestmetrointheworldlctleadershackathon2024moscowmetroisthebestmetrointheworldlctleadershackathon2024'
    auth-token-validity: 1h
    refresh-token-validity: 7d
    none-same-site-cookies: false
    cors-enables: true
logging:
  level:
    ru.mosmetro.backend: debug
