spring:
  application:
    name: metro-back
  datasource:
    url: 'jdbc:postgresql://localhost:5432/metro_back'
    username: 'postgres'
    password: 'postgres'
springdoc:
  swagger-ui:
    path: '/swagger-ui/'
metro:
  security:
    key-secret: 'moscowmetroisthebestmetrointheworldlctleadershackathon2024moscowmetroisthebestmetrointheworldlctleadershackathon2024'
    auth-token-validity: 1h
    refresh-token-validity: 7d
    none-same-site-cookies: false
    cors-enables: true
logging:
  level:
    ru.mosmetro.backend: debug

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:/metro-back.p12
    key-store-password: qwe123
    key-alias: baeldung