spring:
  application:
    name: metro-back
  datasource:
    url: 'jdbc:postgresql://localhost:5432/metro_back'
    username: 'postgres'
    password: 'postgres'
springdoc:
  swagger-ui:
    path: '/swagger-ui'
